Contiki-Inga 3.x: radio_driver Struct Reference
radio_driver Struct Reference
Radio API
The structure of a device driver for a radio in Contiki.
#include <core/dev/radio.h>
Data Fields
int(* prepare)(const void *payload, unsigned short payload_len)
Prepare the radio with a packet to be sent.
int(* transmit)(unsigned short transmit_len)
Send the packet that has previously been prepared.
int(* send)(const void *payload, unsigned short payload_len)
Prepare & transmit a packet.
int(* read)(void *buf, unsigned short buf_len)
Read a received packet into a buffer.
int(* channel_clear)(void)
Perform a Clear-Channel Assessment (CCA) to find out if there is a packet in the air or not.
int(* receiving_packet)(void)
Check if the radio driver is currently receiving a packet.
int(* pending_packet)(void)
Check if the radio driver has just received a packet.
int(* on)(void)
Turn the radio on.
int(* off)(void)
Turn the radio off.
Detailed Description
The structure of a device driver for a radio in Contiki.
Definition at line 60 of file radio.h.
Field Documentation
int(* radio_driver::channel_clear)(void)
Perform a Clear-Channel Assessment (CCA) to find out if there is a packet in the air or not.
Definition at line 78 of file radio.h.
int(* radio_driver::off)(void)
Turn the radio off.
Definition at line 90 of file radio.h.
Referenced by cc2538_rf_channel_set(), cc2538_rf_read_rssi(), and PROCESS_THREAD().
int(* radio_driver::on)(void)
Turn the radio on.
Definition at line 87 of file radio.h.
Referenced by cc2538_rf_channel_set(), and cc2538_rf_read_rssi().
int(* radio_driver::prepare)(const void *payload, unsigned short payload_len)
Prepare the radio with a packet to be sent.
Definition at line 65 of file radio.h.
int(* radio_driver::read)(void *buf, unsigned short buf_len)
Read a received packet into a buffer.
Definition at line 74 of file radio.h.
Referenced by PROCESS_THREAD().
int(* radio_driver::send)(const void *payload, unsigned short payload_len)
Prepare & transmit a packet.
Definition at line 71 of file radio.h.
int(* radio_driver::transmit)(unsigned short transmit_len)
Send the packet that has previously been prepared.
Definition at line 68 of file radio.h.