Contiki-Inga 3.x: cpu/cc2430/dev/cc2430_rf.h File Reference
cc2430_rf.h File Reference
    CC2430 RF driver header file
#include "contiki.h"
#include "dev/radio.h"
#include "cc2430_sfr.h"
Functions
void cc2430_rf_command (uint8_t command)
Execute a single CSP command.
int8_t cc2430_rf_channel_set (uint8_t channel)
Select RF channel.
uint8_t cc2430_rf_power_set (uint8_t new_power)
Select RF transmit power.
void cc2430_rf_set_addr (unsigned pan, unsigned addr, const uint8_t *ieee_addr)
Set MAC addresses.
void cc2430_rf_ISR (void) __interrupt(RF_VECTOR)
RF interrupt service routine.
Detailed Description
    CC2430 RF driver header file
Author
Zach Shelby zach@.nosp@m.sens.nosp@m.inode.nosp@m..com
Definition in file cc2430_rf.h.
Function Documentation
int8_t cc2430_rf_channel_set (uint8_t channel)
Select RF channel.
Parameters
channel channel number to select
Returns
channel value or negative (invalid channel number)
Definition at line 180 of file cc2430_rf.c.
References cc2430_rf_command().
void cc2430_rf_command (uint8_t command)
Execute a single CSP command.
Parameters
command command to execute
Definition at line 122 of file cc2430_rf.c.
References clock_delay_usec().
Referenced by cc2430_rf_channel_set(), cc2430_rf_send_ack(), and random_init().
uint8_t cc2430_rf_power_set (uint8_t new_power)
Select RF transmit power.
Parameters
new_power new power level
Returns
new level
Definition at line 219 of file cc2430_rf.c.
void cc2430_rf_set_addr (unsigned pan, unsigned addr, const uint8_t * ieee_addr)
Set MAC addresses.
Parameters
pan The PAN address to set
addr The short address to set
ieee_addr The 64-bit IEEE address to set
Definition at line 252 of file cc2430_rf.c.
References NULL.