Contiki-Inga 3.x: Rime addresses
Rime addresses
The Rime communication stack
The linkaddr module is an abstract representation of addresses in Rime.
Files
file linkaddr.c
    Functions for manipulating Rime addresses
file linkaddr.h
    Header file for the Rime address representation
Functions
void linkaddr_copy (linkaddr_t *dest, const linkaddr_t *from)
Copy a Rime address.
int linkaddr_cmp (const linkaddr_t *addr1, const linkaddr_t *addr2)
Compare two Rime addresses.
void linkaddr_set_node_addr (linkaddr_t *addr)
Set the address of the current node.
Variables
linkaddr_t linkaddr_node_addr
The Rime address of the node.
linkaddr_t linkaddr_node_addr
The Rime address of the node.
const linkaddr_t linkaddr_null
The null Rime address.
Detailed Description
The linkaddr module is an abstract representation of addresses in Rime.
Function Documentation
int linkaddr_cmp (const linkaddr_t * addr1, const linkaddr_t * addr2)
Compare two Rime addresses.
Parameters
addr1 The first address
addr2 The second address
Returns
Non-zero if the addresses are the same, zero if they are different
        This function compares two Rime addresses and returns
        the result of the comparison. The function acts like
        the '==' operator and returns non-zero if the addresses
        are the same, and zero if the addresses are different.
Examples:
example-collect.c, example-multihop.c, example-runicast.c, and example-unicast.c.
Definition at line 66 of file linkaddr.c.
Referenced by mac_LowpanToEthernet(), mac_sequence_is_duplicate(), mac_sequence_register_seqno(), sicslowmac_dataRequest(), and uip_ds6_link_neighbor_callback().
void linkaddr_copy (linkaddr_t * dest, const linkaddr_t * from)
Copy a Rime address.
Parameters
dest The destination
from The source
        This function copies a Rime address from one location
        to another.
Examples:
example-collect.c, example-multihop.c, and example-runicast.c.
Definition at line 60 of file linkaddr.c.
Referenced by frame802154_parse(), linkaddr_set_node_addr(), and mac_sequence_register_seqno().
void linkaddr_set_node_addr (linkaddr_t * addr)
Set the address of the current node.
Parameters
addr The address
        This function sets the Rime address of the node.
Definition at line 72 of file linkaddr.c.
References linkaddr_copy(), and linkaddr_node_addr.
Variable Documentation
linkaddr_t linkaddr_node_addr
The Rime address of the node.
This variable contains the Rime address of the node. This variable should not be changed directly; rather, the linkaddr_set_node_addr() function should be used.
Examples:
example-announcement.c, example-collect.c, example-multihop.c, example-rucb.c, example-rudolph1.c, example-rudolph2.c, example-runicast.c, example-trickle.c, and example-unicast.c.
Definition at line 48 of file linkaddr.c.
Referenced by abc_input(), abc_send(), broadcast_send(), cc2538_rf_set_addr(), ipolite_send(), linkaddr_set_node_addr(), main(), and mesh_send().
linkaddr_t linkaddr_node_addr
The Rime address of the node.
This variable contains the Rime address of the node. This variable should not be changed directly; rather, the linkaddr_set_node_addr() function should be used.
Definition at line 48 of file linkaddr.c.
const linkaddr_t linkaddr_null
The null Rime address.
This variable contains the null Rime address. The null address is used in route tables to indicate that the table entry is unused. Nodes with no configured address has the null address. Nodes with their node address set to the null address will have problems communicating with other nodes.
Examples:
example-collect.c.
Referenced by frame802154_parse(), mac_LowpanToEthernet(), sicslowmac_dataRequest(), and uip_ds6_link_neighbor_callback().