Contiki-Inga 3.x: Polite anonymous best effort local broadcast
Polite anonymous best effort local broadcast
The Rime communication stack
The polite module sends one local area broadcast packet within one time interval.
Files
file polite.c
    Polite Anonymous best effort local area BroadCast (polite)
file polite.h
    Header file for Polite Anonymous best effort local Broadcast (polite)
Data Structures
struct polite_callbacks
A structure with callback functions for a polite connection.
struct polite_conn
An opaque structure with no user-visible elements that holds the state of a polite connection,.
Functions
void polite_open (struct polite_conn *c, uint16_t channel, const struct polite_callbacks *cb)
Open a polite connection.
void polite_close (struct polite_conn *c)
Close a polite connection.
int polite_send (struct polite_conn *c, clock_time_t interval, uint8_t hdrsize)
Send a packet on a polite connection.
void polite_cancel (struct polite_conn *c)
Cancel a pending packet.
Detailed Description
The polite module sends one local area broadcast packet within one time interval.
If a packet with the same header is received from a neighbor within the interval, the packet is not sent.
The polite primitive is a generalization of the polite gossip algorithm from Trickle (Levis et al, NSDI 2004). The polite gossip algorithm is designed to reduce the total amount of packet transmissions by not repeating a message that other nodes have already sent. The purpose of the polite broadcast primitive is to avoid that multiple copies of a specific set of packet attributes is sent on a specified logical channel in the local neighborhood during a time interval.
The polite broadcast primitive is useful for implementing broadcast protocols that use, e.g., negative acknowledgements. If many nodes need to send the negative acknowledgement to a sender, it is enough if only a single message is delivered to the sender.
The upper layer protocol or application that uses the polite broadcast primitive provides an interval time, and message along with a list of packet attributes for which multiple copies should be avoided. The polite broadcast primitive stores the outgoing message in a queue buffer, stores the list of packet attributes, and sets up a timer. The timer is set to a random time during the second half of the interval time.
During the first half of the time interval, the sender listens for other transmissions. If it hears a packet that matches the attributes provided by the upper layer protocol or application, the sender drops the packet. The send timer has been set to a random time some time during the second half of the interval. When the timer fires, and the sender has not yet heard a transmission of the same packet attributes, the sender broadcasts its packet to all its neighbors.
The polite broadcast module does not add any packet attributes to outgoing packets apart from those added by the upper layer.
Channels
The polite module uses 1 channel.
Function Documentation
void polite_cancel (struct polite_conn * c)
Cancel a pending packet.
Parameters
c A pointer to a struct polite_conn that has previously been opened with polite_open().
        This function cancels a pending transmission that has
        previously been started with polite_send().
Definition at line 143 of file polite.c.
References ctimer_stop(), and NULL.
void polite_close (struct polite_conn * c)
Close a polite connection.
Parameters
c A pointer to a struct polite_conn that has previously been opened with polite_open().
        This function closes a polite connection that has
        previously been opened with polite_open().
Definition at line 116 of file polite.c.
References abc_close(), ctimer_stop(), and NULL.
void polite_open (struct polite_conn * c, uint16_t channel, const struct polite_callbacks * cb)
Open a polite connection.
Parameters
c A pointer to a struct polite_conn.
channel The channel number to be used for this connection
cb A pointer to the callbacks used for this connection
        This function opens a polite connection on the
        specified channel. The callbacks are called when a
        packet is received, or when another event occurs on the
        connection (see \ref "struct polite_callbacks").
Definition at line 108 of file polite.c.
References abc_open().
int polite_send (struct polite_conn * c, clock_time_t interval, uint8_t hdrsize)
Send a packet on a polite connection.
Parameters
c A pointer to a struct polite_conn that has previously been opened with polite_open().
interval The timer interval in which the packet should be sent.
hdrsize The size of the header that should be unique within the time interval.
        This function sends a packet from the packetbuf on the
        polite connection. The packet is sent some time during
        the time interval, but only if no other packet is
        received with the same header.
Definition at line 127 of file polite.c.
References ctimer_set(), NULL, and random_rand().