Contiki-Inga 3.x: Routing
Routing
uIP IPv6 specific features
Data Structures
struct uip_ds6_route_neighbor_routes
The neighbor routes hold a list of routing table entries that are attached to a specific neihbor.
struct uip_ds6_route
An entry in the routing table.
struct uip_ds6_route_neighbor_route
A neighbor route list entry, used on the uip_ds6_route->neighbor_routes->route_list list.
struct uip_ds6_defrt
An entry in the default router list.
Macros
#define UIP_DS6_ROUTE_STATE_TYPE rpl_route_entry_t
define some additional RPL related route state and neighbor callback for RPL - if not a DS6_ROUTE_STATE is already set
Typedefs
typedef struct uip_ds6_route uip_ds6_route_t
An entry in the routing table.
typedef struct uip_ds6_defrt uip_ds6_defrt_t
An entry in the default router list.
Functions
void uip_ds6_route_init (void)
Initialize routing.
Default router list basic routines
uip_ds6_defrt_t * uip_ds6_defrt_add (uip_ipaddr_t *ipaddr, unsigned long interval)
Add default router.
void uip_ds6_defrt_rm (uip_ds6_defrt_t *defrt)
Remove default router.
uip_ds6_defrt_t * uip_ds6_defrt_lookup (uip_ipaddr_t *ipaddr)
Lookup default router for address.
uip_ipaddr_t * uip_ds6_defrt_choose (void)
?
void uip_ds6_defrt_periodic (void)
?
Routing Table basic routines
uip_ds6_route_t * uip_ds6_route_lookup (uip_ipaddr_t *destipaddr)
Lookup route for address.
uip_ds6_route_t * uip_ds6_route_add (uip_ipaddr_t *ipaddr, uint8_t length, uip_ipaddr_t *next_hop)
Add route for address.
void uip_ds6_route_rm (uip_ds6_route_t *route)
Remove route.
void uip_ds6_route_rm_by_nexthop (uip_ipaddr_t *nexthop)
uip_ipaddr_t * uip_ds6_route_nexthop (uip_ds6_route_t *)
int uip_ds6_route_num_routes (void)
Number of routes?
uip_ds6_route_t * uip_ds6_route_head (void)
First route?
uip_ds6_route_t * uip_ds6_route_next (uip_ds6_route_t *)
Next route?
Detailed Description
Function Documentation
uip_ds6_defrt_t* uip_ds6_defrt_add (uip_ipaddr_t * ipaddr, unsigned long interval)
Add default router.
Definition at line 486 of file uip-ds6-route.c.
References list_push(), memb_alloc(), NULL, stimer_set(), uip_ds6_defrt_lookup(), and uip_ipaddr_copy.
Referenced by uip_nd6_ra_input().
uip_ds6_defrt_t* uip_ds6_defrt_lookup (uip_ipaddr_t * ipaddr)
Lookup default router for address.
Definition at line 565 of file uip-ds6-route.c.
References list_head(), list_item_next(), and NULL.
Referenced by uip_ds6_defrt_add(), uip_ds6_neighbor_periodic(), uip_nd6_na_input(), and uip_nd6_ra_input().
void uip_ds6_defrt_rm (uip_ds6_defrt_t * defrt)
Remove default router.
Definition at line 534 of file uip-ds6-route.c.
References list_head(), list_item_next(), list_remove(), memb_free(), and NULL.
Referenced by uip_ds6_defrt_periodic(), uip_ds6_neighbor_periodic(), uip_nd6_na_input(), and uip_nd6_ra_input().
uip_ds6_route_t* uip_ds6_route_add (uip_ipaddr_t * ipaddr, uint8_t length, uip_ipaddr_t * next_hop)
Add route for address.
Definition at line 245 of file uip-ds6-route.c.
References list_add(), LIST_STRUCT_INIT, memb_alloc(), memb_free(), NULL, uip_ds6_nbr_lladdr_from_ipaddr(), uip_ds6_route_head(), uip_ds6_route_lookup(), uip_ds6_route_num_routes(), uip_ds6_route_rm(), UIP_DS6_ROUTE_STATE_TYPE, and uip_ipaddr_copy.
void uip_ds6_route_init (void)
Initialize routing.
Definition at line 140 of file uip-ds6-route.c.
References list_init(), and memb_init().
Referenced by uip_ds6_init().
uip_ds6_route_t* uip_ds6_route_lookup (uip_ipaddr_t * destipaddr)
Lookup route for address.
Definition at line 199 of file uip-ds6-route.c.
References list_add(), list_remove(), NULL, uip_ds6_route_head(), and uip_ds6_route_next().
Referenced by tcpip_ipv6_output(), and uip_ds6_route_add().
void uip_ds6_route_rm (uip_ds6_route_t * route)
Remove route.
Definition at line 375 of file uip-ds6-route.c.
References list_head(), list_item_next(), list_remove(), memb_free(), NULL, uip_ds6_route_head(), and uip_ds6_route_next().
Referenced by tcpip_ipv6_output(), and uip_ds6_route_add().