Contiki-Inga 3.x: cc2538 Random Number Generator
cc2538 Random Number Generator
The cc2538 Development Kit platform
Driver for the cc2538 Hardware Random Number Generator.
Files
file random.c
Random number generator routines exploiting the cc2538 hardware capabilities.
Functions
unsigned short random_rand (void)
Generates a new random number using the cc2538 RNG.
void random_init (unsigned short seed)
Seed the cc2538 random number generator.
Detailed Description
Driver for the cc2538 Hardware Random Number Generator.
Function Documentation
void random_init (unsigned short seed)
Seed the cc2538 random number generator.
Seed the cc253x random number generator.
Parameters
seed Ignored. It's here because the function prototype is in core.
        We form a seed for the RNG by sampling IF_ADC as
        discussed in the user guide.
        Seeding with this method should not be done during
        normal radio operation. Thus, use this function before
        initialising the network.
Note
Must not be called after the RF driver has been initialised and is in normal operation. If it is absolutely necessary to do so, the radio will need re-initialised.
Definition at line 84 of file random.c.
References CC2538_RF_CSP_ISRFOFF, CC2538_RF_CSP_ISRXON, RFCORE_XREG_FRMCTRL0, RFCORE_XREG_RFRND, RFCORE_XREG_RFRND_IRND, RFCORE_XREG_RSSISTAT, RFCORE_XREG_RSSISTAT_RSSI_VALID, SOC_ADC_ADCCON1, SOC_ADC_ADCCON1_RCTRL0, SOC_ADC_ADCCON1_RCTRL1, SOC_ADC_RNDL, and SYS_CTRL_RCGCRFC.
Referenced by main().
unsigned short random_rand (void)
Generates a new random number using the cc2538 RNG.
Generates a new random number using the cc253x RNG.
Returns
The random number.
Definition at line 58 of file random.c.
References SOC_ADC_ADCCON1, SOC_ADC_ADCCON1_RCTRL0, SOC_ADC_RNDH, and SOC_ADC_RNDL.
Referenced by ipolite_send(), polite_send(), uip_ds6_compute_reachable_time(), and uip_ds6_init().