Contiki-Inga 3.x: I2C-Bus Driver
I2C-Bus Driver
Bus Drivers
Functions
int8_t i2c_write (uint8_t data)
Send a byte to I2C bus.
void i2c_stop (void)
Generate I2C STOP condition.
Detailed Description
Function Documentation
int8_t i2c_write (uint8_t data)
Send a byte to I2C bus.
Parameters
data The data that must be sent
Definition at line 105 of file i2c.c.
Referenced by eeprom_read(), eeprom_write(), l3g4200d_get_angle(), l3g4200d_read16bit(), l3g4200d_read8bit(), and l3g4200d_write8bit().